version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ${DATA}/hass:/config
    environment:
      - TZ=${TZ}
    restart: always
    network_mode: host
    
  deconz:
    image: marthoc/deconz
    container_name: deconz
    ports:
      - 8085:80
      - 4043:443
    restart: always
    volumes:
      - ${DATA}/hass/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
